### ISSUE TITLE
Check models

### ISSUE THREAD

**Issue by maticn** [denizgrad/GivEtTip_Case3_Server#1]
I added models. @denizgrad check the annotations of attributes please. They should be fine, just check.

And how do you usually store passwords? I usually use predefined classes in .net, but there, I just wrote one method to hash passwords with sha1.

**Comment by denizgrad** [comment]
I think we should keep them not encrypted. This won't be professional project.


But if you guys insist, let's keep them just in sha1 without a decrypting key.

________________________________

**Comment by hatati** [comment]
Or er could use md5 so we won't need an encryption key? I think that adding encryption is a good praksis so it sits on the backbone.

**Comment by maticn** [comment]
I also think that passwords should be encrypted. I didn't add any "salt" to the hash algorithm and it is no need to change it (I think).

**Comment by denizgrad** [comment]
That was my point, If we are going to encrypt data it should be salted. And so, things get complicated in vein.
And for salt keys to be meaningful, they have to be kept in a seperate table.

But if you two say so, you are the majority and it is democracy😊

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by maticn** [comment]
Just to know: now, we do encrypt passwords and they are salted.
